### ISSUE TITLE
Gmail login error

### ISSUE THREAD

**Issue by bluecode-0** [john-safwat/Chat#44]
**Describe the bug**
Failed to gmail login

**Error message**
PlatfirmException(sign_in_failed, com.google.android.gms.common.api.ApiException:10:, null, null)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S9
 - OS: Android 10

**Comment by john-safwat** [comment]
This problem occurs because the login via Google needs the SHA code to use the login via Google through the Android Studio, and this code differs from one Android Studio version to another and from another device, and this code must be defined inside Firebase Console to make it combatable with Your emulator 
[PlatfirmException error on stack overflow](https://stackoverflow.com/questions/54557479/flutter-and-google-sign-in-plugin-platformexceptionsign-in-failed-com-google)

And if you try the release version on your phone, you will not have a problem logging in 
[Release](https://github.com/john-safwat/Chat/releases/tag/ChatApp)
